services:
  semanticproductsearchexampleapi:
    image: ${DOCKER_REGISTRY-}semanticproductsearchexampleapi
    build:
      context: .
      dockerfile: SemanticProductSearchExampleApi/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - qdrant
      - ollama
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama  # persists models and configs
    restart: unless-stopped
    tty: true  # needed for some models
    environment:
      - OLLAMA_MODELS=/root/.ollama
volumes:
  ollama_data:
